"""
ai_gr.crypto.crl — Certificate Revocation List Management

Handles the revocation of compromised Decentralized Identifiers (DIDs).
Ensures that signatures generated by compromised keys are rejected
if the key was revoked prior to the signature timestamp.
"""

from typing import Dict
from datetime import datetime, timezone

class CertificateRevocationList:
    def __init__(self):
        # In production, this would be backed by PostgreSQL or a Transparency Log.
        # Format: { "did:key:123": "2026-05-18T12:00:00Z" }
        self._revoked_dids: Dict[str, str] = {}

    def revoke_key(self, did: str, revocation_timestamp: str | None = None):
        """
        Revoke a specific DID.
        If no timestamp is provided, defaults to the current UTC time.
        """
        if not revocation_timestamp:
            revocation_timestamp = datetime.now(timezone.utc).isoformat()
        
        self._revoked_dids[did] = revocation_timestamp

    def is_revoked(self, did: str) -> bool:
        """Check if a DID is currently on the revocation list."""
        return did in self._revoked_dids

    def was_revoked_at_time(self, did: str, signature_timestamp: str) -> bool:
        """
        Check if the DID was revoked *before* the signature was created.
        If a signature is created after the revocation timestamp, it is invalid.
        """
        if did not in self._revoked_dids:
            return False
            
        revocation_time = datetime.fromisoformat(self._revoked_dids[did].replace('Z', '+00:00'))
        sig_time = datetime.fromisoformat(signature_timestamp.replace('Z', '+00:00'))
        
        # If the signature happened AFTER the key was revoked, it's invalid.
        return sig_time >= revocation_time

# Global Singleton for the demo
global_crl = CertificateRevocationList()
