"""
ai_gr.regimes.data_act — EU Data Act.

Regulation (EU) 2023/2854. Rules on access to and use of data generated by
connected products and related services. Applies from 12 September 2025.

For AI deployments, the Data Act is most relevant where the AI system is
trained on or processes data from connected products (IoT, industrial
machinery, vehicles), or where the AI is a related service to a connected
product.
"""

from __future__ import annotations

from ai_gr.regimes.base import Regime, RegimeRequirement, _register
from ai_gr.schema import Gate


class DataAct(Regime):
    identifier = "Data-Act"
    name = "EU Data Act (EU 2023/2854)"
    description = (
        "EU regulation on harmonised rules for fair access to and use of data, "
        "including data generated by connected products and related services."
    )

    def requirements(self) -> list[RegimeRequirement]:
        return [
            RegimeRequirement(
                citation="Article 3 — Obligation to make data accessible to users",
                description=(
                    "Connected products and related services shall be designed and "
                    "manufactured so that data generated by use is, by default, easily, "
                    "securely, free of charge and in a comprehensive, structured, commonly "
                    "used and machine-readable format accessible to the user."
                ),
                relevant_gates=(Gate.BUILD, Gate.DEPLOY),
                evidence_needed=(
                    "evidence.additional.data_access_design_attestation",
                ),
            ),
            RegimeRequirement(
                citation="Article 4 — Right of users to access and use data",
                description=(
                    "Where data cannot be directly accessed by the user from the product, "
                    "the data holder shall make readily available data accessible without "
                    "undue delay."
                ),
                relevant_gates=(Gate.OPERATE,),
                evidence_needed=(
                    "operate-gate attestations of data-access fulfilment",
                ),
            ),
            RegimeRequirement(
                citation="Article 5 — Right to share data with third parties",
                description=(
                    "On request by a user, the data holder shall make data available to "
                    "third parties chosen by the user without undue delay."
                ),
                relevant_gates=(Gate.OPERATE,),
                evidence_needed=(
                    "operate-gate attestations of data-sharing requests",
                ),
            ),
            RegimeRequirement(
                citation="Article 33 — Essential requirements for data spaces interoperability",
                description=(
                    "Essential requirements for data sharing, data spaces, and data "
                    "intermediation services."
                ),
                relevant_gates=(Gate.BUILD,),
                evidence_needed=(
                    "evidence.additional.data_space_interop_attestation",
                ),
            ),
        ]


_register(DataAct())
