"""
ai_gr.export.dossier — Regulator-ready dossier export.

Given a GPR chain and a regime identifier, produce a structured dossier
suitable for submission to a regulator or auditor.

For v0.1 we ship two formats:

  - JSON: machine-readable structured dossier
  - Markdown: human-readable narrative dossier

PDF rendering ships in v0.2 (depends on optional jinja2 + reportlab extras).
"""

from __future__ import annotations

import json
from datetime import UTC, datetime
from enum import StrEnum

from ai_gr.regimes import get_regime, list_regimes
from ai_gr.regimes.base import Regime
from ai_gr.schema import GPREntry


class DossierFormat(StrEnum):
    JSON = "json"
    MARKDOWN = "markdown"


def export_dossier(
    chain: list[GPREntry],
    regime_identifier: str,
    *,
    format: DossierFormat = DossierFormat.JSON,
    organization: str = "Organization",
    deployer: str = "Deployer",
) -> str:
    """Export a regulator-ready dossier for one regime.

    Args:
        chain: Ordered GPR chain (root first).
        regime_identifier: Regime identifier (e.g. "EU-AI-Act", "HIPAA").
        format: Output format.
        organization: Org name for the dossier header.
        deployer: Deployer name for the dossier header.

    Returns:
        Dossier as a string in the requested format.
    """
    regime = get_regime(regime_identifier)
    summary = regime.coverage_summary(chain)

    payload = {
        "dossier_metadata": {
            "generated_at": datetime.now(UTC).isoformat(),
            "generator": "ai-gr v0.1.0",
            "organization": organization,
            "deployer": deployer,
            "chain_length": len(chain),
            "chain_root_id": chain[0].id if chain else None,
            "chain_head_id": chain[-1].id if chain else None,
        },
        "regime_coverage": summary,
        "entries": [e.to_jsonld() for e in chain if regime.applies_to_entry(e)],
    }

    if format == DossierFormat.JSON:
        return json.dumps(payload, indent=2, default=str)
    elif format == DossierFormat.MARKDOWN:
        return _render_markdown(payload, regime)
    else:
        raise ValueError(f"Unknown format: {format!r}")


def multi_regime_dossier(
    chain: list[GPREntry],
    *,
    regime_identifiers: list[str] | None = None,
    organization: str = "Organization",
) -> str:
    """Export a single dossier that maps the chain across multiple regimes.

    This is the "build the evidence once; map it many times" deliverable.
    """
    regimes_to_use: list[Regime] = (
        [get_regime(r) for r in regime_identifiers] if regime_identifiers else list_regimes()
    )

    payload = {
        "dossier_metadata": {
            "generated_at": datetime.now(UTC).isoformat(),
            "generator": "ai-gr v0.1.0",
            "organization": organization,
            "chain_length": len(chain),
            "chain_root_id": chain[0].id if chain else None,
            "chain_head_id": chain[-1].id if chain else None,
            "regime_count": len(regimes_to_use),
        },
        "regime_coverage": {r.identifier: r.coverage_summary(chain) for r in regimes_to_use},
        "entries": [e.to_jsonld() for e in chain],
    }
    return json.dumps(payload, indent=2, default=str)


def _render_markdown(payload: dict[str, object], regime: Regime) -> str:
    meta = payload["dossier_metadata"]
    cov = payload["regime_coverage"]

    md: list[str] = []
    md.append(f"# AI-GR Dossier — {regime.name}\n")
    md.append(f"_Generated by {meta['generator']} on {meta['generated_at']}_\n")
    md.append(f"**Organization:** {meta['organization']}  ")
    md.append(f"**Deployer:** {meta['deployer']}  ")
    md.append(f"**Chain length:** {meta['chain_length']} entries\n")
    md.append("---\n")
    md.append("## Regime overview\n")
    md.append(f"{regime.description}\n")
    md.append(f"- **Claims made by this chain:** {cov['claims_made']}")
    md.append(f"- **Entries contributing evidence:** {cov['entries_covered']}")
    md.append(f"- **Gates covered:** {', '.join(cov['gates_covered'])}\n")

    md.append("## Requirements coverage\n")
    md.append("| Citation | Satisfied | Evidence entries |")
    md.append("|---|---|---|")
    for req in cov["requirements"]:
        status = "✅" if req["satisfied"] else "❌"
        evidence_str = ", ".join(req["evidence_entries"]) if req["evidence_entries"] else "—"
        md.append(f"| {req['citation']} | {status} | {evidence_str} |")
    md.append("")

    md.append("## Chain summary\n")
    for entry_dict in payload["entries"]:
        md.append(f"### `{entry_dict['id']}`")
        md.append(f"- **Gate:** {entry_dict['gate']}")
        md.append(f"- **Tier:** {entry_dict['risk_tier']}")
        md.append(f"- **Decision:** {entry_dict['decision']}")
        md.append(f"- **Subject:** {entry_dict['subject']['system']} v{entry_dict['subject']['version']}")
        md.append("")

    return "\n".join(md)


__all__ = ["DossierFormat", "export_dossier", "multi_regime_dossier"]
